//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdondeVamos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_lugares
    {
        public int IdLugar { get; set; }
        public int IdUsuario { get; set; }
        public string Comentario { get; set; }
    
        public virtual Lugares Lugares { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
