//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdondeVamos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_lugar_historial
    {
        public int IdUsu_lug_hist { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idLugar { get; set; }
        public string coordenadasGoogle { get; set; }
        public string nombreGoogle { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Lugares Lugares { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
