//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdondeVamos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class A_DONDE_VAMOSEntities : DbContext
    {
        public A_DONDE_VAMOSEntities()
            : base("name=A_DONDE_VAMOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Horarios_concurridos> Horarios_concurridos { get; set; }
        public virtual DbSet<Lugares> Lugares { get; set; }
        public virtual DbSet<Promociones> Promociones { get; set; }
        public virtual DbSet<Tipo_Usuarios> Tipo_Usuarios { get; set; }
        public virtual DbSet<Usuario_lugar_historial> Usuario_lugar_historial { get; set; }
        public virtual DbSet<Usuario_lugares> Usuario_lugares { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
