//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdondeVamos.Models
{
    using AdondeVamos.DAL;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public class A_DONDE_VAMOS : DbContext, IDbContext
    {
        public A_DONDE_VAMOS()
            : base("name=A_DONDE_VAMOS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Horarios_concurridos> Horarios_concurridos { get; set; }
        public virtual DbSet<Lugares> Lugares { get; set; }
        public virtual DbSet<Promociones> Promociones { get; set; }
        public virtual DbSet<Seguidores> Seguidores { get; set; }
        public virtual DbSet<Tipo_Usuarios> Tipo_Usuarios { get; set; }
        public virtual DbSet<Usuario_lugar_historial> Usuario_lugar_historial { get; set; }
        public virtual DbSet<Usuario_lugares> Usuario_lugares { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }

        public virtual DbSet<TEntity> SetEx<TEntity>() where TEntity : class
        {
            return base.Set<TEntity>();
        }

        #region IDbContext
        public virtual bool CanUpdate()
        {
            return true;
        }

        Database IDbContext.Database()
        {
            return Database;
        }

        IDbSet<TEntity> IDbContext.Set<TEntity>()
        {
            return SetEx<TEntity>();
        }
        #endregion
    }
}