//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdondeVamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promociones
    {
        public int idPromocion { get; set; }
        public string Descripcion { get; set; }
        public int IdUsuario { get; set; }
        public int IdLugar { get; set; }
    
        public virtual Lugares Lugares { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
